version: '3.7'

x-env:
  &default-env
  env_file:
    - .env

x-volumes:
  &default-volumes
  volumes:
    - .:/app

x-app:
  &default-app
  build: .
  <<: *default-env
  <<: *default-volumes

services:
  bot:
    build: .
    command: bash -c " python3 main.py"
    restart: always
    <<: *default-app
